name: Swift Lint

on: [pull_request]

jobs:
  lint:
    runs-on: macos-14-large
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Xcode 16
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.1.app

      - name: Lint
        run: cd darwin && swiftlint --strict # force to fix warnings too
