name: Swift Lint

on: [pull_request]

jobs:
  lint:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Xcode 14.1
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.1.app

      - name: Lint
        run: cd ios && swiftlint --strict # force to fix warnings too
